os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
script:
  - eval "$(curl -sL https://gist.githubusercontent.com/BrettRToomey/1256d98cce5546c696cc68d9f61ad46f/raw/4af6d4a2bb0df02ffba16f9ed05a37eb93b6c6c1/TravisSwift31)"
  - eval "$(curl -sL https://swift.vapor.sh/codecov)"
